name: رفع الفيديوهات إلى GoFile

on:
  workflow_dispatch:  # يشغل يدوياً فقط

jobs:
  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
    - name: جلب المشروع
      uses: actions/checkout@v3
    
    - name: نصب Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: نصب المكتبات
      run: |
        pip install yt-dlp requests
    
    - name: تشغيل السكربت
      run: python upload.py
